strict-sigcheck = false

[Amazon-Shopping]
enabled = true
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
changelog-keywords = ["Amazon"]
arch = "both"

[Amazon-Shopping.patches]
"github:rushiranpise/morphe-patches" = []

[Block-Blast]
enabled = true
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hungrystudio/block-blast-puzzle-games/"
changelog-keywords = ["Block Blast"]
arch = "both"

[Block-Blast.patches]
"github:rushiranpise/morphe-patches" = []

[Adobe-Acrobat] 
enabled = true
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat/"
changelog-keywords = ["Acrobat"]
arch = "both"

[Adobe-Acrobat.patches]
"github:rushiranpise/morphe-patches" = []

[JioHotstar]
enabled = true
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/"
changelog-keywords = ["JioHotstar"]

[JioHotstar.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []
